# spring:
#   application:
#     name: CONFIG-SERVER
eureka.instance:
  prefer-ip-address: true
  hostname: localhost
  instance-id: ${spring.application.name}:${server.port}
  lease-renewal-interval-in-seconds: 10
  lease-expiration-duration-in-seconds: 30

eureka:
    instance:
        prefer-ip-address: true   
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
          defaultZone: http://localhost:8761/eureka/
